import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Filterbar from '../../components/filter/Filterbar';

import Layout from '../../components/layout/Layout';
import Loading from '../../components/loading/Loading';
import PostsListContainer from '../../components/posts/PostsListContainer';
import { useAxios } from '../../hooks/useAxios';
import { AxiosGetPost, IPost } from '../../interfaces';
import { getPosts, PostsState, requestPosts } from '../../redux/slice/postsSlice';
import { RootState } from '../../redux/store';

const BestMemes: NextPage = () => {
  const dispatch = useDispatch();
  const api = useAxios();

  const [postsList, setPostsList] = useState<IPost[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    dispatch(requestPosts());
    api
      .get(`/post?sort=like`)
      .then(({ data }: AxiosGetPost) => {
        const { posts } = data.data;
        setPostsList(posts);
        dispatch(getPosts(posts));
      })
      .catch(err => setError(err));
  }, []);

  const { isLoading } = useSelector<RootState, PostsState>(state => {
    return state.postsReducer;
  });

  if (error) {
    return <div>Error: {error}</div>;
  }

  return (
    <div>
      <Head>
        <title>Mejores memes - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {isLoading ? (
          <Loading message={'Los mejores memes son los que están por venir'} />
        ) : (
          <div className="flex flex-col min-w-screen w-full sm:w-[512px] lg:w-[1024px] mt-[56px]">
            <div className="flex w-full justify-around items-center mt-4 max-w-[344px] mx-auto">
              <h1 className="font-orelega text-[24px] leading-[26px]">Mejores memes</h1>
              <button className="font-roboto font-bold text-primary text-base leading-[19px] border-2 border-primary rounded-lg py-2 px-4 active:text-secondary active:border-secondary">
                Subir meme
              </button>
            </div>
            <Filterbar />
            <div className="flex flex-col justify-center items-center min-h-[80vh]">
              <PostsListContainer postsList={postsList} />
            </div>
          </div>
        )}
      </Layout>
    </div>
  );
};

export default BestMemes;
