import Head from 'next/head';
import React from 'react';
import Error404 from '../components/404/Error404';
import Layout from '../components/layout/Layout';

function FourOhFour() {
  return (
    <>
      <Head>
        <title>Error 404 - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col min-w-screen w-full sm:w-[512px] lg:w-[1024px] mt-[56px] flex-1 justify-center relative">
          <div className="flex w-full justify-center items-center mt-4 max-w-[344px] mx-auto absolute top-0 right-0 left-0">
            <h1 className="font-orelega text-[24px] leading-[26px]">Error 404</h1>
          </div>
          <div className="px-2 mx-auto">
            <Error404 />
          </div>
        </div>
      </Layout>
    </>
  );
}

export default FourOhFour;
