import { AxiosResponse } from 'axios';
import { getCookies, hasCookie } from 'cookies-next';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import Layout from '../components/layout/Layout';
import PostsContainer from '../components/posts/PostsContainer';
import { useAxios } from '../hooks/useAxios';
import { getData } from '../redux/slice/userDataSlice';

const Home: NextPage = () => {
  const handleUploadMeme = () => {
    //TODO: Redireccionar si no está logueado el usuario
    // const data = useAuthSession();
  };

  const existCookieAccess = hasCookie('access_token');
  const existCookieRefresh = hasCookie('refresh_token');
  const cookies = getCookies() as { access_token: string; refresh_token: string };
  const dispatch = useDispatch();

  useEffect(() => {
    if (existCookieAccess && existCookieRefresh) {
      const api = useAxios(cookies.access_token, cookies.refresh_token);
      api.get('/myinfo').then(({ data }: AxiosResponse) => {
        dispatch(
          getData({ user: { ...data }, access_token: cookies.access_token, refresh_token: cookies.refresh_token })
        );
      });
    }
  }, [cookies]);

  return (
    <div>
      <Head>
        <title>Lo Nuevo - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col min-w-screen w-full sm:w-[512px] lg:w-[1024px] mt-[56px]">
          <div className="flex w-full justify-around items-center mt-4 max-w-[344px] mx-auto">
            <h1 className="font-orelega text-[24px] leading-[26px]">Lo nuevo</h1>
            <button
              className="font-roboto font-bold text-primary text-base leading-[19px] border-2 border-primary rounded-lg py-2 px-4 active:text-secondary active:border-secondary"
              onClick={handleUploadMeme}
            >
              Subir meme
            </button>
          </div>
          <div className="px-2 mx-auto">
            <PostsContainer />
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
