import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import FormRegister from "../../components/formRegister/FormRegister";
import Layout from "../../components/layout/Layout";
const Register: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Register - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col justify-center items-center">
          <FormRegister />
          <Link href="/login">¿Ya tienes una cuenta?</Link>
        </div>
      </Layout>
    </div>
  );
};

export default Register;
