import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { BiArrowBack } from 'react-icons/bi';

import { IPost } from '../../interfaces';

import CardPost from '../../components/cardPost/CardPost';
import Comments from '../../components/comments/Comments';
import Layout from '../../components/layout/Layout';

import { getPostById } from '../../services/api-calls';

const Post: NextPage = () => {
  const router = useRouter();

  const [showTags, setShowTags] = useState<boolean>(false);
  const [postVisited, setPostVisited] = useState<Partial<IPost>>({});

  const id = parseInt(router.query.id as string);

  useEffect(() => {
    getPostById(id).then(post => (post ? setPostVisited(post) : null));
  }, []);

  const handleShowTags = () => {
    setShowTags(prev => !prev);
  };

  const { mediaURL, title, likesCount } = postVisited;

  return (
    <div>
      <Head>
        <title>Post - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col min-w-screen w-full sm:w-[512px] lg:w-[1024px]">
          <div className="flex w-full justify-around items-center mt-4 max-w-[344px] mx-auto">
            <h1 className="font-orelega text-[24px] leading-[26px]">Lo nuevo</h1>
            <div className="flex items-center gap-x-0.5">
              {/* TODO: Volver a la página anterior sin recargar la página */}
              <BiArrowBack className="text-[24px] cursor-pointer text-primary mx-2" onClick={() => router.back()} />
              <p className="font-orelega text-[20px] leading-[26px]">Comentarios</p>
            </div>
          </div>
          <div className="px-2 mx-auto">
            <CardPost
              // La propiedad imageUrl tira un error: Image is missing required "src" property. Al cargar la página
              imageUrl={mediaURL || ''}
              author="el bromas"
              title={title}
            />
          </div>
          <div className="flex flex-col w-full justify-around items-center max-w-[344px] mx-auto px-5 mb-4">
            <div className="w-full h-3 flex justify-end font-roboto">
              <p className="text-sm">{likesCount} me gusta</p>
            </div>
            <div className="flex w-full font-roboto text-primary font-bold mb-2">
              <div className="overflow-hidden">
                <p className="ml-1 cursor-pointer select-none" onClick={handleShowTags}>
                  {showTags ? 'Ocultar Tags' : 'Ver Tags'}
                </p>
                <div
                  className={`flex flex-wrap font-normal gap-2 my-2 transition-all duration-100 ease-out select-none ${
                    showTags ? 'opacity-100 h-auto' : 'opacity-0 h-0'
                  }`}
                >
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Madre</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Final Fantasy</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Foto</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Cosplay</p>
                </div>
              </div>
            </div>
            <div className="w-full border-t-[1px] mb-2"></div>
            <div className="w-full mt-2" id="comments">
              <textarea
                className="w-full px-4 py-3 h-[50px] font-roboto border-[1px] rounded resize-none"
                placeholder="Escribí aquí tu comentario"
              />
              <div className="flex justify-end my-2">
                <button className="font-roboto font-bold text-primary text-base leading-[19px] border-2 border-primary rounded-lg py-2 px-4 active:text-secondary active:border-secondary">
                  Comentar
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-y-5 mt-6 mb-4">
              <Comments />
              <Comments />
              <Comments />
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Post;
