import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import CardPost from '../../components/cardPost/CardPost';
import Comments from '../../components/comments/Comments';
import Layout from '../../components/layout/Layout';

const Post: NextPage = () => {
  const router = useRouter();

  // TODO: traer el posteo con una peticion postById
  const { id } = router.query;

  const [showTags, setShowTags] = useState<boolean>(false);

  const handleShowTags = () => {
    setShowTags(prev => !prev);
  };

  return (
    <div>
      <Head>
        <title>Post - Memex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col min-w-screen w-full sm:w-[512px] lg:w-[1024px]">
          <div className="flex w-full justify-around items-center mt-4 max-w-[344px] mx-auto">
            <h1 className="font-orelega text-[24px] leading-[26px]">Lo nuevo</h1>
            <p className="font-orelega text-[20px] leading-[26px]">Comentarios</p>
          </div>
          <div className="px-2 mx-auto">
            <CardPost imageUrl="/assets/meme-1.png" author="el bromas" score={6.7} title="Videogame" />
          </div>
          <div className="flex flex-col w-full justify-around items-center max-w-[344px] mx-auto px-5 mb-4">
            <div className="w-full h-3 flex justify-end font-roboto">
              <p className="text-sm">5 me gusta</p>
            </div>
            <div className="flex w-full font-roboto text-primary font-bold mb-2">
              <div className="overflow-hidden">
                <p className="ml-1 cursor-pointer select-none" onClick={handleShowTags}>
                  {showTags ? 'Ocultar Tags' : 'Ver Tags'}
                </p>
                <div
                  className={`flex flex-wrap font-normal gap-2 my-2 transition-all duration-500 linear select-none ${
                    showTags ? 'translate-y-0 h-auto' : 'translate-y-[-300px] h-0'
                  }`}
                >
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Madre</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Final Fantasy</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Foto</p>
                  <p className="border-2 border-secondary rounded-3xl text-center py-1 px-4">Cosplay</p>
                </div>
              </div>
            </div>
            <div className="w-full border-t-[1px] mb-2"></div>
            <div className="w-full mt-2">
              <textarea
                className="w-full px-4 py-3 h-[50px] font-roboto border-[1px] rounded resize-none"
                placeholder="Escribí aquí tu comentario"
              />
              <div className="flex justify-end my-2">
                <button className="font-roboto font-bold text-primary text-base leading-[19px] border-2 border-primary rounded-lg py-2 px-4">
                  Comentar
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-y-5 mt-6 mb-4">
              <Comments />
              <Comments />
              <Comments />
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Post;
